### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by AslanAmca** [codedmarve/Newest_42_Exam05_Solution#1]
Hi. I am opening this issue to ask a question about Exam 05. 

Do created or removed objects need to be deleted?

Some examples on GitHub take into account the memory leak situation, others don't use delete for any object.

If you have given the exam, you know the answer, I would appreciate a response.

**Comment by codedmarve** [comment]
Hello,

The SpellBook and TargetGenerator class have a map that should be freed properly. If you saved the return of the clone function in your map (or whatever) when you learn a spell or target like this for instance:
void TargetGenerator::learnTargetType(ATarget * spellPtr)
{
    if (spellPtr)
        book.insert(std::pair<std::string, ATarget *>(spellPtr->getType(), spellPtr->clone()));
}
then you must free the memory return by the clone function.

If you save the original copy of a spell or target in the map like this:
void TargetGenerator::learnTargetType(ATarget * spellPtr)
{
    if (spellPtr)
        book.insert(std::pair<std::string, ATarget *>(spellPtr->getType(), spellPtr));
}
It might be problematic to free because it might be on the stack or heap. I would not recommend this method.

If you are referring to the main function, it is important to note that the exam does not require a main function. The main function provided is for testing purposes.
